[package]
name = "gacha_sim"
version = "0.1.0"
authors = ["Maxiwell Luo <maxluoXIII@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rand = "0.8.3"